

CREATE TABLE dbo.TLOG_MESSAGES
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[JCRE] [datetime] NOT NULL,
	[LOG_LEVEL] int NOT NULL,
	[ORIGIN] [varchar](8000) NULL,
	[SCOPE] [varchar](400) NULL,
	[LOGUSER] [varchar](8000) NULL,
	[DOMAINE] [varchar](8000) NULL,
	MESSAGE_NUMBER BIGINT NOT NULL,
	[LOG_MESSAGE] [varchar](max) NULL,
	
	CONSTRAINT [PK_TLOG_MESSAGES] PRIMARY KEY CLUSTERED 
	(
	[ID]
	) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].TLOG_MESSAGES ADD  CONSTRAINT [DF_TLOG_MESSAGES_JCRE]  DEFAULT (getdate()) FOR [JCRE]
GO


--GRANT SELECT,INSERT ON BRIINTER.MonLogAMoi  TO PUBLIC,REEXP,LSCH;
